// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibfwbijmxmtgvehymrmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliZndiaWpteG10Z3ZlaHltcm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjgwMDQsImV4cCI6MjA2Mzg0NDAwNH0.mOfoROakPcD_PEar6e-MXAK8e3OsAHDd53Za4gtORmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);